version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    command: sh entrypoint.sh
  frontend:
    image: node:15.0.1
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - frontend
